# Generated by Django 4.2.2 on 2023-08-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialid',
            name='number_type',
            field=models.CharField(choices=[('SN', 'Serial Number'), ('IMEI', 'IMEI'), ('CN', 'Card Number')], max_length=100),
        ),
    ]
