# Generated by Django 4.2.2 on 2023-08-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_specialid_number_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('SAMSUNG', 'SAMSUNG'), ('TECNO', 'TECNO'), ('IPHONE', 'IPHONE'), ('HP', 'HP'), ('ITEL', 'ITEL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='specialid',
            name='number_type',
            field=models.CharField(choices=[('SN', 'Serial Number'), ('IMEI', 'IMEI'), ('CN', 'Card Number'), ('MAC', 'MAC Address')], max_length=100),
        ),
    ]
