# Generated by Django 4.2.2 on 2023-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_item_brand_alter_specialid_number_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('SAMSUNG', 'SAMSUNG'), ('TECNO', 'TECNO'), ('IPHONE', 'IPHONE'), ('HP', 'HP'), ('ITEL', 'ITEL'), ('OTHER', 'OTHER')], max_length=100),
        ),
    ]
